verbose: false
instrumentation:
  excludes:
    - src/index.ts
    - src/common/typeguard.ts
reporting:
  print: summary
  reports:
    - lcov
  dir: ./coverage
  watermarks:
    branches: [80, 95]
    functions: [90, 98]
    lines: [80, 95]
    statements: [80, 95]
