language: node_js
cache:
  yarn: true
  directories:
    - node_modules
node_js:
  - "10"
  - "8"
install:
  - yarn
before_script:
script:
  - yarn lint
  - yarn test
after_script:
  - yarn report-coverage
