language: node_js
cache:
  yarn: true
  directories:
    - node_modules
node_js:
  - "10"
  - "8"
  - "6"
install:
  - yarn
before_script:
  - yarn compile
script:
  - yarn lint
  - yarn test
after_success:
